package com.buddhism.model;
// Generated 2012-5-11 11:26:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Administrator generated by hbm2java
 */
public class Administrator  implements java.io.Serializable {


     private Integer id;
     private String adName;
     private String adPassword;
     private int adRandom;
     private int adLevel;
     private Set<Post> posts = new HashSet<Post>(0);

    public Administrator() {
    }

	
    public Administrator(String adName, String adPassword, int adRandom, int adLevel) {
        this.adName = adName;
        this.adPassword = adPassword;
        this.adRandom = adRandom;
        this.adLevel = adLevel;
    }
    public Administrator(String adName, String adPassword, int adRandom, int adLevel, Set<Post> posts) {
       this.adName = adName;
       this.adPassword = adPassword;
       this.adRandom = adRandom;
       this.adLevel = adLevel;
       this.posts = posts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAdName() {
        return this.adName;
    }
    
    public void setAdName(String adName) {
        this.adName = adName;
    }
    public String getAdPassword() {
        return this.adPassword;
    }
    
    public void setAdPassword(String adPassword) {
        this.adPassword = adPassword;
    }
    public int getAdRandom() {
        return this.adRandom;
    }
    
    public void setAdRandom(int adRandom) {
        this.adRandom = adRandom;
    }
    public int getAdLevel() {
        return this.adLevel;
    }
    
    public void setAdLevel(int adLevel) {
        this.adLevel = adLevel;
    }
    public Set<Post> getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set<Post> posts) {
        this.posts = posts;
    }




}


